shop/base/urls.py
from django.urls import path

from base.views import (
    ManufacturerList,
    ManufacturerDetailView,
    ManufacturerCreate,
    ScaleList,
    ScaleCreate,
    ScaleModelList,
    ScaleModelDetailView,
    ScaleModelCreate,
    homepage,
)

app_name = 'base'

urlpatterns = [
    path("", homepage),
    path('manufacturer/', ManufacturerList.as_view(), name="manufacturer-index"),
    path('manufacturer/<int:pk>/', ManufacturerDetailView.as_view(), name="manufacturer-detail"),
    path('manufacturer/create/', ManufacturerCreate.as_view(), name="manufacturer-create"),

    path('scale/', ScaleList.as_view(), name="scale-index"),
    path('scale/create/', ScaleCreate.as_view(), name="scale-create"),

    path('scalemodel/', ScaleModelList.as_view(), name="scalemodel-index"),
    path('scalemodel/<int:pk>/', ScaleModelDetailView.as_view(), name="scalemodel-detail"),
    path('scalemodel/create/', ScaleModelCreate.as_view(), name="scalemodel-create"),
]

shop/myauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from myauth.views import MyUserCreateView

app_name = 'myauth'

urlpatterns = [
    path('register/', MyUserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

shop/shop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls', namespace='base')),
    path('auth/', include('myauth.urls', namespace='myauth')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

shop/base/models/buy.py
from django.db import models

from myauth.models import MyUser
from base.models import ScaleModel


class Buy(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    model = models.ForeignKey(ScaleModel, on_delete=models.PROTECT)
    buy_time = models.DateTimeField(auto_now_add=True)

shop/base/models/manufacturer.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(null=False, blank=True)

    def __str__(self):
        return self.name

shop/base/models/scale.py
from django.db import models


class Scale(models.Model):
    value = models.CharField(max_length=10)

    def __str__(self):
        return self.value

shop/base/models/scalemodel.py
from django.db import models

from base.models import Manufacturer
from base.models import Scale


class ScaleModel(models.Model):
    name = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(
        Manufacturer,
        on_delete=models.SET_NULL,
        null=True,
    )
    scale = models.ForeignKey(
        Scale,
        on_delete=models.PROTECT
    )
    description = models.TextField(null=False, blank=True)

    price = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.name

shop/myauth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    email = models.EmailField('email address', unique=True)
    full_name = models.CharField(max_length=150, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

shop/myauth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from myauth.models import MyUser


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('username', 'email', 'full_name', 'phone_number', 'password1', 'password2')

shop/base/views/homepage.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'base/homepage.html')

shop/base/views/manufacturer.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from base.models import Manufacturer


class ManufacturerDetailView(DetailView):
    model = Manufacturer


class ManufacturerList(ListView):
    model = Manufacturer

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['page_title'] = 'Manufacturer'
        return context


class ManufacturerCreate(CreateView):
    model = Manufacturer
    fields = '__all__'
    success_url = reverse_lazy('base:manufacturer-index')

shop/base/views/scale.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from base.models import Scale


class ScaleList(ListView):
    model = Scale

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['page_title'] = 'Scale list'
        return context


class ScaleCreate(CreateView):
    model = Scale
    fields = '__all__'
    success_url = reverse_lazy('base:scale-index')

shop/base/views/scalemodel.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView

from base.models import ScaleModel


class ScaleModelDetailView(DetailView):
    model = ScaleModel


class ScaleModelList(ListView):
    model = ScaleModel

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['page_title'] = 'Models'
        return context


class ScaleModelCreate(CreateView):
    model = ScaleModel
    fields = '__all__'
    success_url = reverse_lazy('base:scale-index')

shop/myauth/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

from myauth.forms import MyUserCreationForm
from myauth.models import MyUser


class MyUserCreateView(CreateView):
    model = MyUser
    success_url = '/'
    form_class = MyUserCreationForm

shop/base/templates/base/homepage.html
{% extends 'root.html' %}

{% block main %}
    <h2>Список доступных ListView в рамках ДЗ</h2>
    <ul>
        <li>
            <a href="{% url 'base:manufacturer-index' %}">Список производителей</a>
        </li>
        <li>
            <a href="{% url 'base:scale-index' %}">Доступные масштабы </a>
        </li>
        <li>
            <a href="{% url 'base:scalemodel-index' %}">Доступные модели </a>
        </li>
    </ul>
{% endblock %}

shop/base/templates/base/manufacturer_detail.html
{% extends 'root.html' %}

{% block title %}
    {{ manufacturer.name }}
{% endblock %}

{% block main %}
    <h2>{{ manufacturer.name }}</h2>
    <p>{{ manufacturer.description }}</p>
    <form action="{% url 'base:manufacturer-index' %}">
        <input type="submit" value="Back"/>
    </form>
{% endblock %}

shop/base/templates/base/manufacturer_form.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block main %}
    <h2>Manufacturer create</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Сreate">
    </form>
    <form action="{% url 'base:manufacturer-index' %}">
        <input type="submit" value="Back"/>
    </form>
{% endblock %}

shop/base/templates/base/manufacturer_list.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block main %}
    <h2>Manufacturer</h2>
    <ul>
        {% for manufacturer in manufacturer_list %}
            <li>
                <a href="{% url 'base:manufacturer-detail' manufacturer.pk %}">{{ manufacturer }}</a>
            </li>
        {% endfor %}
    </ul>
    <form action="{% url 'base:manufacturer-create' %}">
        <input type="submit" value="Create"/>
    </form>
{% endblock %}

shop/base/templates/base/scale_form.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block main %}
    <h2>Scale create</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Сreate">
    </form>
    <form action="{% url 'base:scale-index' %}">
        <input type="submit" value="Back"/>
    </form>
{% endblock %}

shop/base/templates/base/scale_list.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block main %}
    <h2>Scale list</h2>
    <ul>
        {% for scale in scale_list %}
            <li>
                {{ scale.value }}
            </li>
        {% endfor %}
    </ul>
    <form action="{% url 'base:scale-create' %}">
        <input type="submit" value="Create"/>
    </form>
{% endblock %}

shop/base/templates/base/scalemodel_detail.html
{% extends 'root.html' %}

{% block title %}
    {{ scalemodel.name }}
{% endblock %}

{% block main %}
    <h2>{{ scalemodel.name }}</h2>
    <p>Описание: {{ scalemodel.description }}</p>
    <p>Производитель: {{ scalemodel.manufacturer }}</p>
    <p>Mасштаб: {{ scalemodel.scale }}</p>
    <p>Цена: {{ scalemodel.price }}</p>
    <form action="{% url 'base:scalemodel-index' %}">
        <input type="submit" value="Back"/>
    </form>
{% endblock %}

shop/base/templates/base/scalemodel_form.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block main %}
    <h2>Scale Model create</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Сreate">
    </form>
    <form action="{% url 'base:scalemodel-index' %}">
        <input type="submit" value="Back"/>
    </form>
{% endblock %}

shop/base/templates/base/scalemodel_list.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block main %}
    <h2>Models</h2>
    <ul>
        {% for scalemodel in scalemodel_list %}
            <li>
                <a href="{% url 'base:scalemodel-detail' scalemodel.pk %}">{{ scalemodel }}</a>
            </li>
        {% endfor %}
    </ul>
    <form action="{% url 'base:scalemodel-create' %}">
        <input type="submit" value="Create"/>
    </form>
{% endblock %}

shop/myauth/templates/myauth/myuser_form.html
{% extends 'root.html' %}

{% block main %}
    <div class="login-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="create">
        </form>
    </div>
{% endblock %}

shop/templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
            Scale models Shop
        {% endblock %}
    </title>


    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
<form action="/">
        <input type="submit" value="Home"/>
    </form>
{% block main %}
{% endblock %}

<footer>
    Otus, 2023
</footer>
</body>
</html>